import Head from 'next/head'
import Image from 'next/image'
import Layout from './components/Layout'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='text-4x1'>
       <Layout>
        some stuff inside the layout
       </Layout>
      </div>
    </div>
  )
}
